spring:
  application:
    name: dispatch-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
server:
  port: 8000
  servlet:
    context-path: /
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# for circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      default:
        failureRateThreshold: 1
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 1
      sample-api:
        maxConcurrentCalls: 1
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
# for zipkin
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern: level:%5p [${spring.application.name:}, %X{traceId:-},%X{spanId:-}]
# open api
openapi:
  service:
    title: dispatch-info service doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8765
springdoc:
  api-docs:
    path: /dispatch-service/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /dispatch-service/swagger-ui.html
