spring:
  application:
    name: api-gateway
server:
  port: 8765
  servlet:
    context-path: /
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#spring.cloud.gateway.discovery.locator.enabled=true
# for zipkin
management:
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern: level:%5p [${spring.application.name:}, %X{traceId:-},%X{spanId:-}]

# for springdoc
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-urls: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /location-info/v3/api-docs
        name: Location Service
        primaryName: location Service
      - url: /dispatch-service/v3/api-docs
        name: Dispatch Service
        primaryName: Dispatch Service
