spring:
  application:
    name: api-gateway
server:
  port: 8765
  servlet:
    context-path: /
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
#spring.cloud.gateway.discovery.locator.enabled=true
# for zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: [health, actuator, info]
  info:
    env:
      enabled: true
logging:
  pattern: level:%5p [${spring.application.name:}, %X{traceId:-},%X{spanId:-}]

# for springdoc
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-urls: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /location-info/v3/api-docs
        name: location-info
        primaryName: location-info
      - url: /dispatch-service/v3/api-docs
        name: dispatch-service
        primaryName: dispatch-service
      - url: /dispatch-engine-service/v3/api-docs
        name: Dispatch Engine Service
        primaryName: Dispatch Engine Service
